# -*- coding: utf-8 -*-
"""Hindi_asr_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bk8m7lQ-MbKTr9qFrFMzzKV_1wht1KfY
"""

import os
import whisper


#returns all the audio files found in the directory
def find_audio_files(directory):
    audio_files=[]
    for root, dirs, files in os.walk(directory):
        for file in files:
            #add additional extensions as per requirement
            if any(file.lower().endswith(ext) for ext in ['.wav','.mp3']):
                audio_files.append(os.path.join(root, file))
    return audio_files


#returns text of transcribed audio
def transcribe_audio(file_path, model):
    result = model.transcribe(file_path, language='hi')
    return result['text']


#writes transcription with the audio file in specified output_file
def write_transcriptions_to_file(transcriptions, output_file):
    with open(output_file, 'w', encoding='utf-8') as f:
        for audio_files, transcription in transcriptions.items():
            f.write(f"{audio_files}\t{transcription}\n")


def main():
    #give file path for audio files
    parent_directory = "/Users/Admin/Downloads/GV_Eval_3h/Audio"
    audio_files = find_audio_files(parent_directory)
    #choose any model between small, medium, large, large-v2, large-v3
    model = whisper.load_model("medium")
    transcriptions={}

    for audio_file in audio_files:
        print("Transcribing: {0}".format(audio_file))
        transcription = transcribe_audio(audio_file, model)
        transcriptions[os.path.basename(audio_file)] = transcription
        print(f"{len(transcriptions)}/{len(audio_files)} completed")

    #give path for transcription to be stored followed by text file name
    output_file = "/Users/Admin/Documents/20211cei0063/asr_transcriptions/transcriptions1.txt"
    write_transcriptions_to_file(transcriptions, output_file)
    print("Transcriptions saved to {}".format(output_file))


if __name__ == "__main__":
    main()